"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.
Modified for professional production deployment compatibility.
"""

import os
from pathlib import Path
import dj_database_url  # Parses the deployment database URL string dynamically

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- SECURITY & ENVIRONMENT CONFIGURATIONS ---

# Reads the secret configuration environment variable key or uses a secure local fallback
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 
    'django-insecure-=a#=07&!zmkcquzrm&$7&d%)*(+047w$c#@y6n9x^0$=4ug2%c'
)

# Debug defaults to False in production unless explicitly overridden via variables
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Restricts request access matching specific live domains; defaults to all patterns on Railway
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# --- APPLICATION DEFINITION ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom Application Services
    'users.apps.UsersConfig',
    'academic.apps.AcademicConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serves high-performance static layers in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# --- DATA STORAGE RELATIONAL BACKENDS ---

# Dynamically swaps local SQLite files out for automated cloud PostgreSQL on deployment
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True
    )
}


# --- IDENTITY AUTHENTICATION BARRIERS ---

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = 'login'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- GLOBALIZATION & TEMPORAL METRICS ---

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# --- ASSET COMPILATION LAYERS (STATIC FILES) ---

STATIC_URL = 'static/'

# Local path where asset maps compile during build operations
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configures optimized asset minification and runtime lookup storage layers
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
